#!/usr/bin/env bash

echo -e "fill process name: \c"
read process
echo -e "need source? y/n(default n) \c"
read is_source
if [ ! $is_source ];then
    is_source=n
fi
echo -e "need sync? y/n(default n) \c"
read is_sync
if [ ! $is_sync ];then
    is_sync=n
fi
echo -e "continue? y/n(default y) \c"
read is_start
if [[ $is_start == "n"  ]];then
    exit
fi
mkdir $process
cd $process
touch configure.sh
echo "#!/usr/bin/env bash" >> configure.sh
echo "# auto generated by epack" >> configure.sh
touch install.sh
echo "#!/usr/bin/env bash" >> install.sh
echo "# auto generated by epack" >> install.sh
if [[ $is_source == "y"  ]];then
    touch source.sh
    echo "# auto generated by epack" >> source.sh
    echo "source $process/source.sh" >> ../source.sh
fi
if [[ $is_sync == "y"  ]];then
    touch sync_list

    echo "#!/usr/bin/env bash" >> load.sh
    echo "# auto generated by epack" >> load.sh
    echo "# load settings in epack to your device" >> load.sh
    echo "SYNC_FILES=\$(cat sync_list)" >> load.sh
    echo "for file in \$SYNC_FILES;do" >> load.sh
    echo -e "\tlet base_file=\$(basename \$file)" >> load.sh
    echo -e "\tlet file_owner=\$(ls -l \$file | awk '{print \$3}')" >> load.sh
    echo -e "\tif [[ \$file_owner == 'root' ]];then" >> load.sh
    echo -e "\t\tlet sudo_flag=sudo" >> load.sh
    echo -e "\telse">> load.sh
    echo -e "\t\tlet sudo_flag=" >> load.sh
    echo -e "\tfi" >> load.sh
    echo -e "\tif [ -e \$file ];then" >> load.sh
    echo -e "\t\techo backup \$file to \$file.old" >> load.sh
    echo -e "\t\t\$sudo_flag mv \$file \$file.old" >> load.sh
    echo -e "\tfi" >> load.sh
    echo -e "\t\$sudo_flag cat \$base_file > \$file" >> load.sh
    echo -e "\techo load \$file success" >> load.sh
    echo "done" >> load.sh

    echo "#!/usr/bin/env bash" >> save.sh
    echo "# auto generated by epack" >> save.sh
    echo "# save settings in your device to epack" >> save.sh
    echo "SYNC_FILES=\$(cat sync_list)" >> save.sh
    echo "for file in \$SYNC_FILES;do" >> save.sh
    echo -e "\tlet base_file=\$(basename \$file)" >> save.sh
    echo -e "\tcat \$file > \$base_file" >> save.sh
    echo -e "\techo save \$file success" >> save.sh
    echo "done" >> save.sh
fi

