#!/usr/bin/env bash
# auto generated by epack
# save settings in your device to epack
SYNC_FILES=$(cat sync_list)
for file in $SYNC_FILES;do
	let base_file=$(basename $file)
	cat $file > $base_file
	echo save $file success
done
