#auto generated by epack

start-proxy(){
start-trojan
gsettings set org.gnome.system.proxy mode manual
gsettings set org.gnome.system.proxy.socks host '127.0.0.1'
gsettings set org.gnome.system.proxy.socks port '2333'
export http_proxy=127.0.0.1:8118
export https_proxy=127.0.0.1:8118
export all_proxy=127.0.0.1:8118
git config --global http.proxy socks5://127.0.0.1:2333
git config --global https.proxy socks5://127.0.0.1:2333
}

close-proxy(){
close-trojan
gsettings set org.gnome.system.proxy.socks host ''
gsettings set org.gnome.system.proxy.socks port '0'
gsettings set org.gnome.system.proxy mode none
unset http_proxy
unset https_proxy
unset all_proxy
git config --global --unset http.proxy
git config --global --unset https.proxy
}


