#!/usr/bin/env bash
#auto generated by epack
TO_DIR=~
for file in .zshrc;do
	if [ -e $TO_DIR/$file ];then
		echo backup $TO_DIR/$file to $TO_DIR/$file.old
		sudo mv $TO_DIR/$file $TO_DIR/$file.old
	fi
	sudo cp $file $TO_DIR/$file
	sudo chmod 664 $TO_DIR/$file
	echo load $file success
done
