#!/usr/bin/env bash
#auto generated by epack
FROM_DIR=~
for file in .zshrc;do
	if [ -e $FROM_DIR/$file ];then
		cp $FROM_DIR/$file $file
		echo save $file success
	else
		echo $FROM_DIR$json not exist
	fi
done
